___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>저작권 Pierian Data</em></center>
<center><em>자세한 내용은 <a href='http://www.pieriandata.com'>www.pieriandata.com</a>에서 확인하세요</em></center>

<div class="alert alert-info"><strong>참고:</strong> 보통은 csv 파일을 직접 읽거나 pandas-datareader를 사용해 웹에서 데이터를 가져오게 됩니다. 이 강의는 pandas로 가능한 입출력 기능을 빠르게 훑어보는 개요라고 생각하면 됩니다. 이 과정에서는 SQL이나 Excel 파일을 본격적으로 다루지 않습니다.</div>

# 데이터 입력과 출력

이 노트북은 입력과 출력에 대한 참고 코드입니다. pandas는 다양한 파일 형식을 pd.read_ 계열 메서드로 읽을 수 있습니다. 가장 자주 쓰이는 데이터 형식을 살펴보겠습니다:

In [1]:
import numpy as np
import pandas as pd

## CSV
쉼표로 구분된 값(Comma Separated Values) 파일은 필드를 쉼표로 구분하는 텍스트 파일입니다.<br>
강의에 포함된 가상 환경을 사용하지 않는다면 <tt>xlrd</tt>와 <tt>openpyxl</tt>를 설치해야 할 수 있습니다.<br>
터미널 또는 명령 프롬프트에서 다음을 실행하세요:

    conda install xlrd
    conda install openpyxl

그런 다음 Jupyter Notebook을 다시 시작하세요.
(Anaconda Distribution을 사용하지 않는다면 pip install을 사용해도 됩니다)

### CSV 입력

In [2]:
df = pd.read_csv('example.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV 출력

In [3]:
df.to_csv('example.csv',index=False)

## Excel
Pandas는 MS Excel 파일을 읽고 쓸 수 있습니다. 하지만 이것은 데이터만 가져오며, 수식이나 이미지는 가져오지 않습니다. 이미지나 매크로가 포함된 파일은 <tt>.read_excel()</tt> 메서드가 중단될 수 있습니다.

### Excel 입력

In [4]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Excel 출력

In [5]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

## HTML
Pandas는 HTML에서 표를 읽어올 수 있습니다.<br>
강의에 포함된 가상 환경을 사용하지 않는다면 <tt>lxml</tt>, <tt>html5lib</tt>, <tt>BeautifulSoup4</tt>를 설치해야 할 수 있습니다.<br>
터미널 또는 명령 프롬프트에서 다음을 실행하세요:

    conda install lxml
    conda install html5lib
    conda install beautifulsoup4

그런 다음 Jupyter Notebook을 다시 시작하세요.
(Anaconda Distribution을 사용하지 않는다면 pip install을 사용해도 됩니다)

### HTML 입력

Pandas의 read_html 함수는 웹페이지에 있는 표를 읽어서 DataFrame 객체의 리스트로 반환합니다:

In [6]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [8]:
df[0].head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Washington Federal Bank for Savings,Chicago,IL,30570,Royal Savings Bank,"December 15, 2017","February 21, 2018"
1,The Farmers and Merchants State Bank of Argonia,Argonia,KS,17719,Conway Bank,"October 13, 2017","February 21, 2018"
2,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb","May 26, 2017","July 26, 2017"
3,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,"May 5, 2017","March 22, 2018"
4,First NBC Bank,New Orleans,LA,58302,Whitney Bank,"April 28, 2017","December 5, 2017"

____

# 잘하셨습니다!