___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>저작권 Pierian Data</em></center>
<center><em>자세한 내용은 <a href='http://www.pieriandata.com'>www.pieriandata.com</a>에서 확인하세요</em></center>

# Pandas 연습문제
이제 새로 익힌 pandas 기술을 시험해볼 시간입니다! 아래 굵게 표시된 작업을 완료하기 위해 Data 폴더의 <tt>population_by_county.csv</tt> 파일을 사용하세요.

<div class="alert alert-info" style="margin: 10px"><strong>참고:</strong> 모든 문제는 pandas 코드 한 줄로 해결할 수 있습니다. 막혀도 괜찮습니다. 해설 노트북을 확인하세요!</div>

<div class="alert alert-danger" style="margin: 10px"><strong>중요!</strong> 예시 출력 바로 위에 있는 셀을 실행하지 않도록 주의하세요. <br>그렇지 않으면 예시 출력이 덮어써질 수 있습니다!</div>

#### 1. pandas를 import하고 <tt>population_by_county.csv</tt> 파일을 읽어 <tt>pop</tt>이라는 데이터프레임으로 저장하세요.

In [1]:
import pandas as pd

In [2]:
pop = pd.read_csv('../Data/population_by_county.csv')

#### 2. 데이터프레임의 head를 출력하세요.

In [ ]:
# 여기에 코드 작성

In [ ]:
# 여기에 작성하지 마세요
pop.head()

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054

#### 3. 열 이름은 무엇인가요?

In [ ]:
# 여기에 작성하지 마세요
pop.columns

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')

<strong>4. 이 데이터셋에는 몇 개의 주(State)가 포함되어 있나요?</strong> <em>참고: 이 데이터에는 District of Columbia도 포함되어 있습니다</em>

In [ ]:
# 여기에 작성하지 마세요
pop['State'].nunique()

51

#### 5. 이 데이터셋에 포함된 모든 주(State)의 목록 또는 배열을 구하세요.

In [ ]:
# 여기에 작성하지 마세요
pop['State'].unique()

array(['South Carolina', 'Louisiana', 'Virginia', 'Idaho', 'Iowa',
       'Kentucky', 'Missouri', 'Oklahoma', 'Colorado', 'Illinois',
       'Indiana', 'Mississippi', 'Nebraska', 'North Dakota', 'Ohio',
       'Pennsylvania', 'Washington', 'Wisconsin', 'Vermont', 'Minnesota',
       'Florida', 'North Carolina', 'California', 'New York', 'Wyoming',
       'Michigan', 'Alaska', 'Maryland', 'Kansas', 'Tennessee', 'Texas',
       'Maine', 'Arizona', 'Georgia', 'Arkansas', 'New Jersey',
       'South Dakota', 'Alabama', 'Oregon', 'West Virginia',
       'Massachusetts', 'Utah', 'Montana', 'New Hampshire', 'New Mexico',
       'Rhode Island', 'Nevada', 'District of Columbia', 'Connecticut',
       'Hawaii', 'Delaware'], dtype=object)

#### 6. 미국에서 가장 흔한 County 이름 5개는 무엇인가요?

In [ ]:
# 여기에 작성하지 마세요
pop['County'].value_counts().head()

Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: County, dtype: int64

#### 7. 2010년 인구조사 기준으로 인구가 가장 많은 County 5개는 무엇인가요?

In [ ]:
# 여기에 작성하지 마세요
pop.sort_values('2010Census', ascending=False).head()

                  County       State  2010Census  2017PopEstimate
1713  Los Angeles County  California     9818605         10163507
628          Cook County    Illinois     5194675          5211263
1209       Harris County       Texas     4092459          4652980
1784     Maricopa County     Arizona     3817117          4307033
2501    San Diego County  California     3095313          3337685

#### 8. 2010년 인구조사 기준으로 인구가 가장 많은 주(State) 5개는 무엇인가요?

In [ ]:
# 여기에 작성하지 마세요
pop.groupby('State').sum().sort_values('2010Census', ascending=False).head()

            2010Census  2017PopEstimate
State
California    37253956         39536653
Texas         25145561         28304596
New York      19378102         19849399
Florida       18801310         20984400
Illinois      12830632         12802023

#### 9. 2010년 인구가 100만 명을 넘는 County는 몇 개인가요?

In [ ]:
# 여기에 작성하지 마세요
# pop['2010Census'].apply(lambda qty: qty>1000000).value_counts()
sum(pop['2010Census']>1000000)

39

#### 10. 이름에 "County"라는 단어가 들어가지 않는 County는 몇 개인가요?

In [ ]:
# 여기에 작성하지 마세요
# pop['County'].apply(lambda name: 'County' not in name).value_counts()
sum(pop['County'].apply(lambda name: 'County' not in name))

135

#### 11. 2010년 인구조사와 2017년 인구 추정치 사이의 증감률을 계산하는 열을 추가하세요.

In [ ]:
# 여기에 코드 작성

# 결과를 확인하려면 이것을 사용하세요
pop.head()

In [ ]:
# 여기에 작성하지 마세요
pop['PercentChange'] = 100*(pop['2017PopEstimate']-pop['2010Census'])/pop['2010Census']
pop.head()

,County,State,2010Census,2017PopEstimate,PercentChange
0,Abbeville County,South Carolina,25417,24722,-2.734390
1,Acadia Parish,Louisiana,61773,62590,1.322584
2,Accomack County,Virginia,33164,32545,-1.866482
3,Ada County,Idaho,392365,456849,16.434697
4,Adair County,Iowa,7682,7054,-8.174954

<strong>보너스: 2010년 인구조사와 2017년 인구 추정치 사이의 예상 증감률이 가장 높은 주(State)는 어디인가요?</strong><br>이 문제는 PercentChange를 다시 계산해야 하므로 여러 줄의 코드가 필요합니다.

In [ ]:
# 여기에 코드 작성

In [ ]:
# 여기에 작성하지 마세요
pop2 = pd.DataFrame(pop.groupby('State').sum())
pop2['PercentChange'] = 100*(pop2['2017PopEstimate']-pop2['2010Census'])/pop2['2010Census']
pop2.sort_values('PercentChange', ascending=False).head()

                      2010Census  2017PopEstimate  PercentChange
State
District of Columbia      601723           693972      15.330808
Texas                   25145561         28304596      12.562993
North Dakota              672591           755393      12.310899
Utah                     2763885          3101833      12.227282
Florida                 18801310         20984400      11.611372

# 정말 잘하셨습니다!